apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: liferay-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:ifnazar/liferay-argocd.git
        revision: v2
        directories:
          - path: liferay/apps/*/environments/*
  template:
    metadata:
      name: '{{path[4]}}-{{path[2]}}'
      annotations:
        argocd.argoproj.io/sync-wave: |
          {{- if eq path[2] "nginx" -}}0
          {{- else if eq path[2] "elasticsearch" -}}1
          {{- else if eq path[2] "liferay" -}}2
          {{- end }}
    spec:
      project: default

      source:
        repoURL: git@github.com:ifnazar/liferay-argocd.git
        targetRevision: v2
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[2]}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true